---
name: receive-pr

on:
  workflow_call:
    inputs:
      recipe:
        description: The OpenRewrite recipe to apply to the PR
        type: string
        required: false
        default: org.openrewrite.recipes.OpenRewriteBestPractices
      rewrite_yml:
        description: The contents of the rewrite.yml file to apply to the PR
        type: string
        required: false
        default: |
          ---
      init_gradle:
        description: The Gradle init script to apply to the PR
        type: string
        required: false
        default: |
          initscript {
            repositories {
              maven { url 'https://plugins.gradle.org/m2' }
            }
            dependencies {
              classpath('org.openrewrite:plugin:latest.release')
            }
          }
          rootProject {
            plugins.apply(org.openrewrite.gradle.RewritePlugin)
            dependencies {
                rewrite('org.openrewrite.recipe:rewrite-recommendations:latest.release')
            }
            afterEvaluate {
              if (repositories.isEmpty()) {
                repositories {
                  mavenCentral()
                }
              }
            }
          }

env:
  GRADLE_SWITCHES: --console=plain --info --stacktrace --warning-mode=all --no-daemon -Dorg.gradle.jvmargs=-Xmx2g

# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
# Since this pull request receives untrusted code, we should **NOT** have any secrets in the environment.
jobs:
  upload-patch:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Capture the PR number
      - name: Create pr_number.txt
        run: echo "${{ github.event.number }}" > pr_number.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt
      - name: Remove pr_number.txt
        run: rm -f pr_number.txt

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Apply license headers
      - name: Apply license headers
        run: ./gradlew ${{ env.GRADLE_SWITCHES }} licenseFormat

      # Execute best practices recipe
      - name: Create temporary files
        run: |
          echo "${{ inputs.rewrite_yml }}" > rewrite.yml
          echo "${{ inputs.init_gradle }}" > rewrite-init.gradle
      - name: Apply OpenRewrite best practices
        run: ./gradlew ${{ env.GRADLE_SWITCHES }} rewriteRun --init-script rewrite-init.gradle -Drewrite.activeRecipe=${{ inputs.recipe }}
      - name: Remove temporary files
        run: rm -f rewrite.yml rewrite-init.gradle

      # Capture the diff
      - name: Create patch
        run: |
          git diff > git-diff.patch
          cat git-diff.patch
      - uses: actions/upload-artifact@v4
        with:
          name: patch
          path: git-diff.patch
