---
name: repository-backup

on:
  workflow_call:
    inputs:
      bucket_storage_service_url:
        description: The URL to the object storage service. (e.g. https://s3.amazonaws.com, https://s3.us-west-2.amazonaws.com, etc.). See https://docs.aws.amazon.com/general/latest/gr/s3.html for AWS.
        type: string
        default: https://s3.us-west-2.amazonaws.com
        required: false
      bucket_region:
        description: AWS region of the backup bucket.
        type: string
        default: us-west-2
        required: false
    secrets:
      bucket_access_key_id:
        description: Value of the object storage bucket backup access key ID (e.g., S3 has ACCESS_KEY_ID).
        required: true
      bucket_secret_access_key:
        description: Value of the object storage bucket backup secret access key (e.g., S3 has ACCESS_KEY_SECRET).
        required: true
      bucket_mirror_target:
        description: Name of the object storage bucket backup to use.
        required: true

jobs:
  repository-backup:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openrewrite'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          show-progress: false
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ inputs.bucket_region }}
          role-to-assume: arn:aws:iam::297794628946:role/repository-backups-openrewrite-github-actions-role
      - name: Mirror repository to S3
        timeout-minutes: 30
        env:
          AWS_ENDPOINT_URL_S3: ${{ inputs.bucket_storage_service_url }}
          MIRROR_TARGET: ${{ secrets.bucket_mirror_target }}/${{ github.repository }}
        run: aws s3 sync --delete --no-follow-symlinks --no-progress . "s3://$MIRROR_TARGET"
